--[[
	Bagnon Config Localization Information: Brasilian Portuguese
--]]

local L = LibStub('AceLocale-3.0'):NewLocale('Bagnon-Config', 'ptBR')

L.Columns = 'Colunas'
L.Scale = 'Escala'
L.Spacing = 'Espaçamento'
L.Opacity = 'Transparência'
L.FrameColor = 'Cor de Fundo'
L.FrameBorderColor = 'Cor do Bordo'
L.Frame = 'Janela'
L.Inventory = 'Sacos'
L.Bank = 'Banco'
L.GuildBank = 'Guild Bank'
L.LockFramePositions = 'Bloquear posição das janelas'
L.ShowEmptyItemSlotBackground = 'Display a background for empty item slots'
L.HighlightItemsByQuality = 'Realçar itens por qualidade' 
L.HighlightUnusableItems = 'Realçar itens inutilizáveis'
L.HighlightQuestItems = 'Realçar itens de missão'
L.ReverseSlotOrdering = 'Reverse bag slot ordering'
L.ColorItemSlotsByBagType = 'Color empty item slots by bag type'
L.FrameLayer = 'Camada'
L.EnableBagFrame = 'Mostrar lista de sacos'
L.EnableMoneyFrame = 'Mostrar dinheiro'
L.EnableDBOFrame = 'Mostrar DataBroker'
L.EnableSearchToggle = 'Mostrar botão da pesquisa'
L.EnableOptionsToggle = 'Mostrar botão da configração'
L.EnableFrame_inventory = 'Ativar janela dos sacos'
L.EnableFrame_bank = 'Ativar janela do banco'
L.SettingRequiresRestart = 'This setting will take effect the next time you log in'

L.EnableAutoDisplay_bank = 'Display inventory when visiting the bank'
L.EnableAutoDisplay_ah = 'Display inventory when visiting the auction house'
L.EnableAutoDisplay_vendor = 'Close inventory when leaving a vendor'
L.EnableAutoDisplay_trade = 'Display inventory when trading items'
L.EnableAutoDisplay_craft = 'Display inventory when crafting'
L.EnableAutoDisplay_mail = 'Display inventory when checking a mailbox'
L.EnableAutoDisplay_guildbank = 'Display inventory when visiting the guild bank'
L.EnableAutoDisplay_player = 'Display inventory when opening the player frame'
L.EnableAutoDisplay_combat = 'Close inventory when entering combat'
L.EnableAutoDisplay_vehicle = 'Close inventory when entering a vehicle'

L.DisplaySettings = 'Automatic Display'
L.DisplaySettingsTitle = 'Automatic frame display settings'
L.FrameSettings = 'Frame Settings'
L.FrameSettingsTitle = 'Configuration settings specific to a Bagnon frame'
L.GeneralSettings = 'General Settings'
L.GeneralSettingsTitle = 'General configuration settings for Bagnon'
L.EnableBlizzardBagPassThrough = 'Display Blizzard frames for disabled bags'
L.EnableBagBreak = 'Enable bag break layout'
L.ColorSettings = 'Color Settings'
L.ColorSettingsTitle = 'Item slot coloring settings'
L.ItemHighlightOpacity = 'Item highlight brightness'
L.EnableFlashFind = 'Enable flash find'
L.EnableTipCount = 'Enable tooltip item count'

L.ItemSlotColor_normal = 'Normal bag slot color'
L.ItemSlotColor_leather = 'Leatherworking bag slot color'
L.ItemSlotColor_inscri = 'Inscription bag slot color'
L.ItemSlotColor_herb = 'Herbalism bag slot color'
L.ItemSlotColor_enchant = 'Enchanting bag slot color'
L.ItemSlotColor_engineer = 'Engineering bag slot color'
L.ItemSlotColor_gem = 'Gem bag slot color'
L.ItemSlotColor_mine = 'Mining bag slot color'
L.ItemSlotColor_tackle = 'Tackle box slot color'